# Generated by Django 4.2.20 on 2025-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_group_alter_post_options_alter_comment_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("-created",),
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={"verbose_name": "Follow", "verbose_name_plural": "Follows"},
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                check=models.Q(("user", models.F("following")), _negated=True),
                name="check_not_self_follow",
            ),
        ),
    ]
