# Generated by Django 5.1.7 on 2025-03-10 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_follow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Group", "verbose_name_plural": "Groups"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                condition=models.Q(("user", models.F("following")), _negated=True),
                name="check_not_self_follow",
            ),
        ),
    ]
