# Generated by Django 5.1.7 on 2025-03-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_group_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="check_not_self_follow",
        ),
    ]
