# Generated by Django 5.1.7 on 2025-03-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_follow_prevent_self_follow_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
    ]
